// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"tribemedia.io/m/ent/pgsodiumconfig"
	"tribemedia.io/m/ent/project"
)

// PgsodiumConfigCreate is the builder for creating a PgsodiumConfig entity.
type PgsodiumConfigCreate struct {
	config
	mutation *PgsodiumConfigMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (pcc *PgsodiumConfigCreate) SetProjectID(u uuid.UUID) *PgsodiumConfigCreate {
	pcc.mutation.SetProjectID(u)
	return pcc
}

// SetEnabled sets the "enabled" field.
func (pcc *PgsodiumConfigCreate) SetEnabled(b bool) *PgsodiumConfigCreate {
	pcc.mutation.SetEnabled(b)
	return pcc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (pcc *PgsodiumConfigCreate) SetNillableEnabled(b *bool) *PgsodiumConfigCreate {
	if b != nil {
		pcc.SetEnabled(*b)
	}
	return pcc
}

// SetID sets the "id" field.
func (pcc *PgsodiumConfigCreate) SetID(u uuid.UUID) *PgsodiumConfigCreate {
	pcc.mutation.SetID(u)
	return pcc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pcc *PgsodiumConfigCreate) SetNillableID(u *uuid.UUID) *PgsodiumConfigCreate {
	if u != nil {
		pcc.SetID(*u)
	}
	return pcc
}

// SetProject sets the "project" edge to the Project entity.
func (pcc *PgsodiumConfigCreate) SetProject(p *Project) *PgsodiumConfigCreate {
	return pcc.SetProjectID(p.ID)
}

// Mutation returns the PgsodiumConfigMutation object of the builder.
func (pcc *PgsodiumConfigCreate) Mutation() *PgsodiumConfigMutation {
	return pcc.mutation
}

// Save creates the PgsodiumConfig in the database.
func (pcc *PgsodiumConfigCreate) Save(ctx context.Context) (*PgsodiumConfig, error) {
	pcc.defaults()
	return withHooks(ctx, pcc.sqlSave, pcc.mutation, pcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pcc *PgsodiumConfigCreate) SaveX(ctx context.Context) *PgsodiumConfig {
	v, err := pcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcc *PgsodiumConfigCreate) Exec(ctx context.Context) error {
	_, err := pcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcc *PgsodiumConfigCreate) ExecX(ctx context.Context) {
	if err := pcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pcc *PgsodiumConfigCreate) defaults() {
	if _, ok := pcc.mutation.Enabled(); !ok {
		v := pgsodiumconfig.DefaultEnabled
		pcc.mutation.SetEnabled(v)
	}
	if _, ok := pcc.mutation.ID(); !ok {
		v := pgsodiumconfig.DefaultID()
		pcc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcc *PgsodiumConfigCreate) check() error {
	if _, ok := pcc.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "PgsodiumConfig.project_id"`)}
	}
	if _, ok := pcc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PgsodiumConfig.enabled"`)}
	}
	if _, ok := pcc.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "PgsodiumConfig.project"`)}
	}
	return nil
}

func (pcc *PgsodiumConfigCreate) sqlSave(ctx context.Context) (*PgsodiumConfig, error) {
	if err := pcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pcc.mutation.id = &_node.ID
	pcc.mutation.done = true
	return _node, nil
}

func (pcc *PgsodiumConfigCreate) createSpec() (*PgsodiumConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &PgsodiumConfig{config: pcc.config}
		_spec = sqlgraph.NewCreateSpec(pgsodiumconfig.Table, sqlgraph.NewFieldSpec(pgsodiumconfig.FieldID, field.TypeUUID))
	)
	if id, ok := pcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pcc.mutation.Enabled(); ok {
		_spec.SetField(pgsodiumconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := pcc.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pgsodiumconfig.ProjectTable,
			Columns: []string{pgsodiumconfig.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PgsodiumConfigCreateBulk is the builder for creating many PgsodiumConfig entities in bulk.
type PgsodiumConfigCreateBulk struct {
	config
	err      error
	builders []*PgsodiumConfigCreate
}

// Save creates the PgsodiumConfig entities in the database.
func (pccb *PgsodiumConfigCreateBulk) Save(ctx context.Context) ([]*PgsodiumConfig, error) {
	if pccb.err != nil {
		return nil, pccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pccb.builders))
	nodes := make([]*PgsodiumConfig, len(pccb.builders))
	mutators := make([]Mutator, len(pccb.builders))
	for i := range pccb.builders {
		func(i int, root context.Context) {
			builder := pccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PgsodiumConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pccb *PgsodiumConfigCreateBulk) SaveX(ctx context.Context) []*PgsodiumConfig {
	v, err := pccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pccb *PgsodiumConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := pccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pccb *PgsodiumConfigCreateBulk) ExecX(ctx context.Context) {
	if err := pccb.Exec(ctx); err != nil {
		panic(err)
	}
}
