// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthConfig is the predicate function for authconfig builders.
type AuthConfig func(*sql.Selector)

// Branch is the predicate function for branch builders.
type Branch func(*sql.Selector)

// CustomHostname is the predicate function for customhostname builders.
type CustomHostname func(*sql.Selector)

// Function is the predicate function for function builders.
type Function func(*sql.Selector)

// NetworkBan is the predicate function for networkban builders.
type NetworkBan func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// PgsodiumConfig is the predicate function for pgsodiumconfig builders.
type PgsodiumConfig func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// Secret is the predicate function for secret builders.
type Secret func(*sql.Selector)

// ThirdPartyAuth is the predicate function for thirdpartyauth builders.
type ThirdPartyAuth func(*sql.Selector)

// TypeScriptType is the predicate function for typescripttype builders.
type TypeScriptType func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
